# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy any selected branch to PxWebMaster at Azure 

on: 
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-2019
  
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.3.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0

      - name: Restore NuGet packages
        run: nuget restore PCAxis.PX-Web.sln

      - name: Publish to folder
        run: msbuild PCAxis.PX-Web.sln /nologo /verbosity:m /p:DeployOnBuild=true /p:Configuration=Release /p:_PackageTempDir="${{ github.workspace }}\to_deploy\"
        
      - name: Copy Azure Configfiles
        run: |
          cp TheAzureConfigFiles/databases.config to_deploy/.
          cp TheAzureConfigFiles/Web.config to_deploy/.
          cp TheAzureConfigFiles/setting.config to_deploy/.
             
      - name: Changing title
        run: sed -i 's/PxWeb 2021 v1/PxWeb 2021 from any selected branch/g' to_deploy/Resources/Languages/pxlang.xml

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: '${{ github.workspace }}\to_deploy\**'


  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PxWebMaster'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_NORWAY_PXWEBMASTER }}
          package: .
